### ISSUE TITLE
Latency Related Query

### ISSUE THREAD

**Issue by Shashankft9** [softonic/node-policy-webhook#8]
Hey, I just came across your comment here: https://github.com/knative/serving/issues/1816#issuecomment-668106001
Even though Knative now has the ability to schedule pods on a particular node, I am working with the version where I cant do this, v0.14.0, so I would want to try this. 

One question: Does this add latency to the pods being scheduled since I guess this is one more hope now in the knative flow, does this maybe effect cold starts too?

**Comment by santinoncs** [comment]
It doesn't. Or it is just imperceptible. We are using this webhook in a lot of workloads, and there is no appreciable latency noticed.
I would say, cold starts spends less time on adminission webhooks than on pod placement/scheduling..etc 
But I cannot backup this opinion with data/metrics.

**Comment by Shashankft9** [comment]
Thanks for the response, sounds promising then, I'll try it out. 
Would you be willing to accept any improvements for this?

**Comment by santinoncs** [comment]
We can close the issue if you agree
